# Site settings
title: Lecture Page
email: chiemi@cs.tsukuba.ac.jp
baseurl: "/lectures" # the subpath of your site, e.g. /blog/
url: "http://chiemi627.github.io" # the base hostname & protocol for your site
twitter_username: chiemi_wtnb 
github_username:  chiemi627

# Build settings
markdown: kramdown
